build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
  armhf: ghcr.io/home-assistant/armhf-base:3.21
  armv7: ghcr.io/home-assistant/armv7-base:3.21
  amd64: ghcr.io/home-assistant/amd64-base:3.21
  i386: ghcr.io/home-assistant/i386-base:3.21
args:
  MDNS_REPEATER_VERSION: master
labels:
  org.opencontainers.image.title: Home Assistant Multicast Add-on
  org.opencontainers.image.description: Home Assistant Add-on for Multicast Repeating
  org.opencontainers.image.source: https://github.com/gamorris/ha-multicast-repeater
  org.opencontainers.image.authors: GAM
  org.opencontainers.image.licenses: Apache License 2.0
