name: Build plugin

on:
  pull_request:
    branches: ["master"]
  release:
    types: ["published"]
  push:
    branches: ["master"]
    paths:
    - Dockerfile
    - build.yaml
    - 'rootfs/**'

env:
  BUILD_NAME: multicast
  BUILD_TYPE: plugin

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      version: ${{ steps.version.outputs.version }}
      channel: ${{ steps.version.outputs.channel }}
      publish: ${{ steps.version.outputs.publish }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Get information
      id: info
      uses: home-assistant/actions/helpers/info@master

    - name: Get version
      id: version
      uses: home-assistant/actions/helpers/version@master
      with:
        type: ${{ env.BUILD_TYPE }}

  build:
    name: Build ${{ matrix.arch }} plugin
    needs: init
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4.2.2
   
    - name: Login to GitHub Container Registry
      if: needs.init.outputs.publish == 'true'
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set build arguments
      if: needs.init.outputs.publish == 'false'
      run: echo "BUILD_ARGS=--test" >> $GITHUB_ENV

    - name: Build plugin
      uses: home-assistant/builder@2025.03.0
      with:
        args: |
          $BUILD_ARGS \
          --${{ matrix.arch }} \
          --target /data \
          --cosign \
          --generic ${{ needs.init.outputs.version }}
